### ISSUE TITLE
highlight colour makes text unreadable

### ISSUE THREAD

**Issue by classabbyamp** [miaowware/miaowware-sphinx-theme#4]
![image](https://user-images.githubusercontent.com/5366828/105415415-adc72200-5c06-11eb-828c-56689c41b1cf.png)
![image](https://user-images.githubusercontent.com/5366828/105415429-b1f33f80-5c06-11eb-8674-d5fff4e5edc8.png)
![image](https://user-images.githubusercontent.com/5366828/105415441-b586c680-5c06-11eb-87cd-c718e5798464.png)

should only need to add this then change the colour:
```css
dt:target, span.highlighted {
    background-color: #fbe54e;
}

rect.highlighted {
    fill: #fbe54e;
}
```
